server:
  port: 8003

spring:
  application:
    name: service-vod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.25.132:80

aliyun:
  vod:
    file:
      keyid: LTAI5t7HD6ccvJffdziMdVTN
      keysecret: oDYKN9OB0vphSS7kaY5rkt02qRTVMY