server:
  port: 8001

spring:
  application:
    name: service-edu
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.132:8066/guli?serverTimezone=GMT%2B8
    username: root
    password: YUFhNzM5NzcxNDA5
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.25.132:80


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - com/at/eduservice/mapper/xml/*.xml

#logging:
#  level: info