server:
  port: 8002

spring:
  application:
    name: service_oss
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 3MB
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.25.132:80

aliyun:
  oss:
    file:
      endpoint: oss-cn-chengdu.aliyuncs.com
      keyid: LTAI
      keysecret: oDYKN
      bucketname: edu-guli-102
