server:
  port: 8002

spring:
  application:
    name: service_oss
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 3MB

aliyun:
  oss:
    file:
      endpoint: oss-cn-chengdu.aliyuncs.com
      keyid: xxx
      keysecret: xxx
      bucketname: edu-guli-102
